version: '3.8'
services:
  api:
    # doesnt have to be same name as folder - just doing it for clarity
    build: ./api # folder to build image 
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:./app # hostPath:containerPath (relative)
      - ./app/node_modules # anon volume
  myblog:
    build: ./myblog # folder to build image 
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true # stdin and tty start the container in interactive mode (opposite of detached mode)
    tty: true
